### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by agjarso** [acodexm/Panorama360#2]
hello sir,

i tried to run your code and encountered this problem, do you mind telling me what is the issue? Thank you.
<img width="954" alt="untitled" src="https://user-images.githubusercontent.com/6151155/35484075-df2c2dc0-044a-11e8-86ba-1b5c92fc5990.png">

**Comment by acodexm** [comment]
Please double check if you have ButterKnife setup correctly (Gradle and onCreate). This error is caused by uninitialized "rightBtn" which should be injected by @BindView(R.id.right_btn) otherwise NullPointerExceprion will be thrown.

**Comment by reddfoxx1998** [comment]
which gradle? the project one or the module one? do i need to add this in build.gradle - android?

 compile 'com.jakewharton:butterknife:8.8.1'

currently the the set up i have is the same as you have it here.

**Comment by acodexm** [comment]
No need to add anything to android module gradle. Add your dependencies only on main gradle file for all modules if needed. Pull the latest commit, ensure that you are compiling on gradle-2.14.1-all.zip, if butterknife still doesn't work than try google the problem. This project is indeed hard to setup.

**Comment by reddfoxx1998** [comment]
Lol okay Thank you.

**Comment by reddfoxx1998** [comment]
<img width="1165" alt="2" src="https://user-images.githubusercontent.com/6151155/35576850-5aedc1da-05e0-11e8-8da3-d135c74e0da8.png">
Update: app is running quite well despite some of the functions not working like taking a pic.

anyway one final question. gradle sync works perfectly fine but when cleaning and rebuilding some errors relating to NDK pop up, i have searched on google and nothing of substance comes up. how is your Application.mk looking like?

attached: gradle working well, after building errors pop up
<img width="805" alt="1" src="https://user-images.githubusercontent.com/6151155/35576845-5787a06a-05e0-11e8-9768-b8028e46014d.png">

**Comment by acodexm** [comment]
to get rid of those errors (warnings) please download older version of NDK like ndk-bundle-r15 because on newest version some things are now deprecated.
Please tell me more about not working taking picture. I'm curious about the errors or anything that is related to your issue

**Comment by reddfoxx1998** [comment]
i'll try those suggested solutions later today, thank you.

the shutter simply doesn't work, on manual it displays "can't take picture here" even when i am not moving around. In Auto it simply does nothing but display the record button. Also the absolute save path storage/emulated/0...there is nothing :/

**Comment by reddfoxx1998** [comment]
Hello sir, do you have any idea or solution of what the problem might be?  Thank you. Best regards.

**Comment by acodexm** [comment]
This project is not final, and it wasn't tested on other devices than motoXstyle. If you can build this project  than play with it... disable steady move or tweak it (inside AndroidCamera.java), if folders are not created for some reason than do it manually, if you "can't take picture here" than change area size. most of methods and functions are commented so you shouldn't have problems

**Comment by agjarso** [comment]
Hello,

long time since i checked in, how is the progress going so far?
