### ISSUE TITLE
Hello ,a mistake when build project 

### ISSUE THREAD

**Issue by 5669146xing** [acodexm/Panorama360#4]
![@5 C958)$JB6M0W77AS~{Q4](https://user-images.githubusercontent.com/23392653/54670638-091dba00-4b2f-11e9-924a-f814564c082b.png)
can you help me,thanks

**Comment by acodexm** [comment]
you need specific version of OpenCV https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.3.1/opencv-3.3.1-android-sdk.zip/download
more recent releases won't work
